version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: education_math_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fl4shsimp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3001
      FRONTEND_ORIGIN: http://localhost:3000
      COOKIE_SECRET: change_me
      OLLAMA_BASE_URL: http://192.168.0.197:11434p
      OLLAMA_MODEL: qwen3:32b
      ELEVENLABS_API_KEY: "sk_537cb86234434a3ac68a0d6184bee6e7d86dbde633f4964b"
      ELEVENLABS_VOICE_ID: "Bwff1jnzl1s94AEcntUq"
      ELEVENLABS_MODEL_ID: ""
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: fl4shsimp
      DB_DATABASE: education_math_db
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3001
    ports:
      - "3000:3000"

volumes:
  pgdata:
